### ISSUE TITLE
ng dropover watchers count in page with a lot of elements - performance

### ISSUE THREAD

**Issue by jordan112** [Verical/ngDropover#2]
Do you guys have any performance suggestions/strategies for rendering screens with a large number of elements that all have popovers to help keep watcher count down?  Currently, its one watcher per element.

PS:  Great work on this dropover.  We have moved to this from ns-popover.

**Comment by santhony7** [comment]
We are checking it out now and see your point. The watcher was added so that a user could change the dropover options on the fly but maybe that feature isn't worth the watcher. We are considering making a new option called "liveOptions" or something that would enable the watcher if someone needed it. So the default behavior would be "static" options.

Thanks! We use it a lot and it seems to be working well.

**Comment by jordan112** [comment]
That's a good approach.  I'm thinking most of the time I don't need the two way binding (but still would want to enable it if needed).  We have a variety of screens that are grids and they all the cells have dropovers.  We added some hacky stuff where we get around it with event bubbling.

+1

**Comment by santhony7** [comment]
Okay. I am not sure when we will be able to get to this but I will be sure to update you when we do.

**Comment by rickysandoval** [comment]
@jordan112 Sorry we took a while but you should be able to pass a staticOptions: true along with the config to remove the watches. We defaulted to false in order to not break anything it's currently used on but we might look at making it static by default in the future.
